services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: inopsdockers/openjdk14-mvn-gcloud-kubctl
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

