services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: jelastic/maven:3.9.0-openjdk-20.ea-b34
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

